echo Install libraries
pip install pyTelegramBotAPI
pip install pyautogui
pip install playsound
pip install beautifulsoup4
pip install Pillow
pip install requests
pip install pynput 
pip install opencv-python
